### ISSUE TITLE
CI should be run automatically on toolbox release

### ISSUE THREAD

**Issue by 0xTim** [vapor/homebrew-tap#35]
A few versions of the toolbox have been released since the tap was updated - this should be automated

**Comment by tanner0101** [comment]
This tap is deprecated now since `vapor` has been added to Homebrew directly: https://github.com/Homebrew/homebrew-core/blob/master/Formula/vapor.rb

I'm not sure there's a way to automate pushing to them but that would be nice (that issue should go on vapor/toolbox).

This tap will stay around for the foreseeable future for `vapor-beta` and `vapor3` formulas that give backward compat.

**Comment by 0xTim** [comment]
Will open an issue on the toolbox then!
